CREATE TABLE FEMP_ALLOWED
(
  SEQ_USERID      NUMBER,
  SEQ_SURVEYTYPE  NUMBER
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX NDX_FEMP_ALLOWED ON FEMP_ALLOWED
(SEQ_USERID, SEQ_SURVEYTYPE)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NDX_FEMP_ALLOWED2 ON FEMP_ALLOWED
(SEQ_SURVEYTYPE, SEQ_USERID)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE FEMP_COMMENTS
(
  SEQ_SURVEYTYPE    NUMBER                      NOT NULL,
  STR_COMMENTTAG    VARCHAR2(50 BYTE)           NOT NULL,
  STR_COMMENTLABEL  VARCHAR2(1800 BYTE)
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX NDX_FEMP_COMMENTS ON FEMP_COMMENTS
(SEQ_SURVEYTYPE, STR_COMMENTTAG)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE FEMP_LIST
(
  SEQ_SURVEYTYPE  NUMBER,
  INT_QUESTION    NUMBER,
  INT_LIST        NUMBER,
  STR_LABEL       VARCHAR2(500 BYTE)            DEFAULT '',
  RAW_IMGBLOB     LONG RAW                      DEFAULT null,
  STR_CONTENT     VARCHAR2(32 BYTE)             DEFAULT null,
  BLN_INSURVEY    VARCHAR2(1 BYTE)              DEFAULT 'T'
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NDX_FEMP_LIST ON FEMP_LIST
(SEQ_SURVEYTYPE, INT_QUESTION, INT_LIST)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE FEMP_QUESTIONS
(
  SEQ_SURVEYTYPE     NUMBER,
  INT_QUESTION       NUMBER,
  BLN_REQUIRED       VARCHAR2(1 BYTE)           DEFAULT 'F',
  STR_QUESTIONTYPE   VARCHAR2(1 BYTE),
  LNG_VALUE          VARCHAR2(1800 BYTE),
  BLN_FILTER         VARCHAR2(1 BYTE)           DEFAULT 'T',
  STR_GRAPHTYPE      VARCHAR2(5 BYTE)           DEFAULT 'PIE',
  INT_REPORTGROUP    INTEGER                    DEFAULT 0,
  BLN_TOPISNOTAPP    VARCHAR2(1 BYTE)           DEFAULT 'F',
  BLN_VISIBLECHOICE  VARCHAR2(1 BYTE)           DEFAULT 'F',
  BLN_INSURVEY       VARCHAR2(1 BYTE)           DEFAULT 'T',
  BLN_NULLTRACK      VARCHAR2(1 BYTE)           DEFAULT 'T'
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NDX_FEMP_QUESTION ON FEMP_QUESTIONS
(SEQ_SURVEYTYPE, INT_QUESTION)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE FEMP_REPORTGROUP
(
  INT_REPORTGROUP  INTEGER,
  STR_LABEL        VARCHAR2(200 CHAR),
  SEQ_SURVEYTYPE   INTEGER
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_FEMP_REPORTGROUP ON FEMP_REPORTGROUP
(SEQ_SURVEYTYPE, INT_REPORTGROUP)
LOGGING
TABLESPACE TQ
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE FEMP_REPORTGROUP ADD (
  CONSTRAINT PK_FEMP_REPORTGROUP
  PRIMARY KEY
  (SEQ_SURVEYTYPE, INT_REPORTGROUP)
  USING INDEX PK_FEMP_REPORTGROUP);

CREATE TABLE FEMP_REPORTGROUPLIST
(
  INT_REPORTGROUP  INTEGER,
  STR_LISTLABEL    VARCHAR2(200 CHAR),
  SEQ_SURVEYTYPE   INTEGER,
  INT_LIST         INTEGER
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_FEMP_REPORTGROUPLIST ON FEMP_REPORTGROUPLIST
(SEQ_SURVEYTYPE, INT_REPORTGROUP, INT_LIST)
LOGGING
TABLESPACE TQ
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE FEMP_REPORTGROUPLIST ADD (
  CONSTRAINT PK_FEMP_REPORTGROUPLIST
  PRIMARY KEY
  (SEQ_SURVEYTYPE, INT_REPORTGROUP, INT_LIST)
  USING INDEX PK_FEMP_REPORTGROUPLIST);

CREATE TABLE FEMP_RESPONSE
(
  SEQ_USERID     NUMBER,
  SEQ_SURVEY     NUMBER,
  DAT_CREATED    DATE,
  DAT_DATEUSED   DATE,
  DAT_REMIND     DATE,
  INT_SUBMITTED  NUMBER                         DEFAULT 0,
  DAT_COMPLETE   DATE,
  INT_COMPLETE   NUMBER                         DEFAULT 0
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX NDX_FEMP_RESPONSE ON FEMP_RESPONSE
(SEQ_USERID, SEQ_SURVEY)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE FEMP_RESULTS
(
  SEQ_SURVEY        NUMBER                      NOT NULL,
  SEQ_USERID        NUMBER                      NOT NULL,
  DAT_DATE          DATE                        NOT NULL,
  INT_QUESTION      NUMBER                      NOT NULL,
  STR_QUESTIONTYPE  VARCHAR2(1 BYTE),
  INT_VALUE         NUMBER,
  INT_SUBMITTED     NUMBER                      NOT NULL,
  LNG_VALUE         VARCHAR2(4000 BYTE)         DEFAULT '',
  INT_CY            NUMBER,
  INT_MONTH         NUMBER,
  INT_DAY           NUMBER,
  INT_FY            NUMBER
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NDX_FEMP_RESULTS ON FEMP_RESULTS
(SEQ_SURVEY, SEQ_USERID, INT_QUESTION, INT_SUBMITTED)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NDX_FEMP_RESULTS02 ON FEMP_RESULTS
(SEQ_SURVEY, DAT_DATE, STR_QUESTIONTYPE, INT_QUESTION, INT_VALUE)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NDX_FEMP_RESULTS03 ON FEMP_RESULTS
(SEQ_SURVEY, STR_QUESTIONTYPE, INT_QUESTION, INT_VALUE)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE FEMP_RESULTS ADD (
  CONSTRAINT NDX_FEMP_RESULTS
  PRIMARY KEY
  (SEQ_SURVEY, SEQ_USERID, INT_QUESTION, INT_SUBMITTED)
  USING INDEX NDX_FEMP_RESULTS);

CREATE TABLE FEMP_SURVEY
(
  SEQ_SURVEY      NUMBER,
  INT_CREATEDBY   NUMBER,
  SEQ_SURVEYTYPE  NUMBER,
  DAT_CLOSING     DATE,
  LNG_COMMENTS    VARCHAR2(1800 BYTE),
  STR_SYMBOL      VARCHAR2(16 BYTE)             DEFAULT ' ',
  BLN_OPTIONAL    VARCHAR2(1 BYTE)              DEFAULT 'F',
  BLN_ACTIVE      VARCHAR2(1 BYTE)              DEFAULT 'T',
  STR_COLOR       VARCHAR2(8 BYTE)              DEFAULT '008080',
  INT_SUBMITTED   NUMBER                        DEFAULT 0,
  STR_SURVEYAUTH  VARCHAR2(50 BYTE)             DEFAULT ''
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE FEMP_TEMPLATES
(
  SEQ_SURVEYTYPE    NUMBER,
  STR_TEMPLATENAME  VARCHAR2(50 BYTE),
  LNG_DESCRIPTION   VARCHAR2(1800 BYTE),
  DAT_DATECREATED   DATE,
  BLN_ACTIVE        VARCHAR2(1 BYTE)            DEFAULT 'T',
  INT_CREATEDBY     NUMBER,
  BLN_TRAINING      VARCHAR2(1 BYTE)            DEFAULT 'F',
  BLN_OPTIONAL      VARCHAR2(1 BYTE)            DEFAULT 'F'
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE FEMP_USERS
(
  BLN_ACTIVE         VARCHAR2(1 BYTE)           DEFAULT 'T',
  BLN_NOEMAIL        VARCHAR2(1 BYTE)           DEFAULT 'F',
  BLN_TRAINING       VARCHAR2(1 BYTE)           DEFAULT 'F',
  DAT_DATECREATED    DATE,
  DAT_DATEUSED       DATE,
  INT_CREATEDBY      NUMBER,
  INT_USERTYPE       NUMBER,
  SEQ_USERID         NUMBER,
  STR_ALTID          VARCHAR2(128 BYTE)         DEFAULT '',
  STR_AUTHENTICATOR  VARCHAR2(150 BYTE),
  STR_COMPANY        VARCHAR2(200 BYTE),
  STR_EMAIL          VARCHAR2(128 BYTE),
  STR_FIRSTNAME      VARCHAR2(50 BYTE),
  STR_HANFORDID      VARCHAR2(7 BYTE)           DEFAULT '',
  STR_IP             VARCHAR2(64 BYTE)          DEFAULT '',
  STR_LASTNAME       VARCHAR2(50 BYTE),
  STR_MIDDLENAME     VARCHAR2(50 BYTE),
  STR_NAMESUFFIX     VARCHAR2(5 BYTE),
  STR_WORKPHONE      VARCHAR2(32 BYTE)
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NDX_FEMP_USERS ON FEMP_USERS
(STR_EMAIL)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE FEMP_USERTYPE
(
  INT_USERTYPE  NUMBER,
  STR_LABEL     VARCHAR2(128 BYTE)
)
TABLESPACE TQ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NDX_FEMP_USERTYPE ON FEMP_USERTYPE
(INT_USERTYPE)
LOGGING
TABLESPACE TQ_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;













