<div id="leftNav">
<h2>Quick Links</h2>
<ul>
<li><a href="/default.asp" id="elhome">Enterprise Learning Home</a></li>
<li><a href="http://hr.pnl.gov/index.stm">HR Home</a></li>
<li><a href="http://ods.pnl.gov">ODS Home</a></li>
</ul>
 	
<h2>Listen and Learn</h2>

<ul>
<li>
<a href="/el-video/default.asp"  title="Windows Media Video">Video Home</a></li>
</ul>

<h2>Training</h2>

<ul>
<li><a href="/trainview/default.asp" id="mytrain">Your Training Record</a></li>
<li><a href="/catalog/default.asp" id="catalog">Training Catalog</a></li>
<li><a href="/sched.asp" id="sched">Training Schedule</a></li>
<li><a href="/instr_qual.asp" id="inst">Qualified Instructors</a></li>
<li><a href="/onlinetraining.asp" id="online">On-Line Training</a></li>
<li><a href="/reading/default.asp">Required Readings</a></li>
<li><a href="/calendar/default.asp">Training Calendar</a></li>
<li><a href="/formsTOC.asp">Training Forms</a></li>
<li><a href="https://hrms.pnl.gov/psp/ps/?cmd=login">PeopleSoft&trade; Log-in</a></li>
</ul>

<h2>New Hire &amp; Visitor Information</h2>
<ul>
<li><a href="/orientadmin/">Orientation Administration</a>
</li>

<li><a href="/VisitorGuide">Visitor Orientation Booklet</a></li>
<li><a href="/trainview/HIDLookup.asp">Hanford ID Lookup</a></li>
<li><a href="/maps.asp">Campus Maps</a></li></ul>

<h2>Performance Data </h2>

<ul>
<li><a href="/pi-stats/default.asp">Metrics, Presentations and Reports</a></li>

<li><a href="http://training.pnl.gov/orient_costs.asp">New Hire Orientation Costs</a></li>
</ul>
<h2>Contact Us</h2>
 <ul>
  <li><a title="A list of EL staff and their area of responsibility along with links to photographs and contact information." href="/stafflist.asp" id="elstafflist">By Staff</a></li>
  <li><a title="A list of contacts for each PNNL course sortable by course title, course number, or contact name.  Also included are links to the Course Catalog and e-mail functionality." href="/Trg_POCs.asp">By Subject Matter Expert</a></li>
  <li><a title="A list of the designated Training Coordinators within PNNL sortable by org code, department, or name." href="/TCs/IOPS_Email.asp">By Training Coordinator</a></li>
<li><a href="/org/D2300-OrgChart.ppt" title="">Organization Chart </a></li>
</ul>

</div>