<div id="leftNav">
	<h2 class="first">Navigation Category</h2>
	<ul>
		<li><a href="template_3col.stm" id="">3-Column Template</a></li>
		<li><a href="template_2col.stm" id="">2-Column Template</a></li>
		<li><a href="template_1col.stm" id="">1-Column Template</a></li>
	</ul>
	
	<h2>Navigation Category 2</h2>
	<ul>
		<li><a href="" id="">Page 1</a></li>
		<li><a href="" id="">Page 2</a></li>
		<li><a href="" id="">Page 3</a></li>
	</ul>
	
	<h2>Navigation Category 2</h2>
	<ul>
		<li><a href="" id="">Page 1</a></li>
		<li><a href="" id="">Page 2</a></li>
		<li><a href="" id="">Page 3</a></li>
	</ul>
</div>