<div id="rightCol">
<h2>Other Websites</h2>

<h3>PNNL External EL Training</h3>
<ul>
<li><a href="http://online-training.pnl.gov/default.asp">Log In</a>  and/or <a href="/register/default.asp">Register</a></li>
<li><a href="/extcourses.asp"> External EL Training Courses </a></li>
<li><a href="http://lessons.pnl.gov/">PNNL Lessons Learned-Operating Experience</a></li></ul> 

<h2>Hot off the Press!</h2>

<ul><li><a href="/whatsnew.asp">What's New</a></li></ul>
<ul><li><a href="/el-newsroom">EL Newsroom</a></li></ul>

<h2>Resources</h2>

<ul>
<li><a href="javascript:WinPop('popups/CourseExtensionListing.pdf',800,600,1)">Course Extension Listing</a></li>
<li><a href="/iops.asp">Integrated Operations System (IOPS)</a></li>
<li><a href="jets.asp">Job Evaluation Training System (JETS)</a></li>
<li><a href="http://sbms.pnl.gov/mgtsys/ms0ud010.htm">Management System Description</a></li> 
<li><a href="peoplesoft.asp">PeopleSoft&trade; Reports</a></li>
<li><a href="links.asp">Related Websites</a></li>
<li><a href="http://sbms.pnl.gov/nav/nv02d020.htm">SBMS Training Subject Areas</a></li></ul>

<h2>Training Tools</h2>

<ul>
<li><a href="popups/ElectricalSafetyTraining.pdf">Electrical Safety Training </a></li>
<li><a href="rad.asp">Radworker Training </a></li>
<li><a href="newsletters/default.asp">Rad Worker News</a></li>
<li><a href="http://infosource-appsnet.pnl.gov/training/default.stm">Software Training (Infosource)</a></li>
<li><a href="http://safetynet.pnl.gov/videos/">Safety Video Library</a></li>
<li><a href="reading_admin/default.asp">RA Admin</a><img src="images/lock.gif" alt="Restricted Access" width="14" height="14" hspace="4" /></li>
<li><a href="billing_admin/roster_admin.asp">Billing/Roster Admin</a><img src="images/lock.gif" alt="Restricted Access" width="14" height="14" hspace="4" /></li>
<li>
<a href="course_statistics/tmp_search.asp">Training Statistics</a><img src="images/lock.gif" alt="Restricted Access" width="14" height="14" hspace="4" /></li>

<li>
    <a title="A web-based training application lookup tool providing status of each student's progress." href="course_statistics/default.asp">WBT Student Status</a>

<span class="red"><img src="images/lock.gif" alt="Restricted Access" width="14" height="14" hspace="4" /></span></li>
</ul>


</div>