<div id="topBanner">
  <a id="pnnlLogo" href="http://www.pnl.gov/">Pacific Northwest National Laboratory</a>
  <a id="skipNav" href="#main"><span>Skip to Main Content</span></a>
  <a id="doeLink" href="http://www.energy.gov/">U.S. Department of Energy</a>
  
  <div id="siteNav">
    <form method="get" action="http://search.pnl.gov/search" name="pnnlsearch" id="pnnlSearch">    
          <input type="hidden" name="as_sitesearch" value="" />
          <input type="hidden" name="access" value="a" />
          <input type="hidden" name="output" value="xml_no_dtd" />
          <input type="hidden" name="client" value="default_frontend" />
          <input type="hidden" name="site" value="default_collection" />
          <input type="hidden" name="proxystylesheet" value="default_frontend" />
          <input type="hidden" name="as_dt" value="i" />    

      <label for="q">Search PNNL Intranet</label>
      <input type="text" name="q" id="q" maxlength="2047" value="" />
      <!-- <button class="copper">Contact Us</button> -->
      <input type="image" id="searchSubmit" src="https://css.pnl.gov/images/search_button.png" alt="Search" />
    </form>
    
    <ul id="pnnlNav">
      <li><a href="http://labweb.pnl.gov/default.aspx" id="home">LabWeb</a></li>
      <li><a href="http://labweb.pnl.gov/topicindex/" id="topicindex">Topic Index</a></li>
      <li><a href="http://sbms.pnl.gov" id="sbms">SBMS</a></li>
      <li><a href="http://www.pnl.gov" id="pnnl_home">PNNL External</a></li>
    </ul>
  </div>
</div>