<div id="footer">
  <div id="footerBar">
    <span id="tagline"></span>
    <a id="officeOfScience" href="http://www.er.doe.gov/">Enabled by the Office of Science</a>
  </div>
  <div id="footerLinks">
    <a href="http://www.pnl.gov/disclaimer.asp">Security &amp; Privacy</a> | <a href="mailto:labweb@pnl.gov">Contact Labweb</a>
  </div>
  <span class="footerItem">Last Update: <span class="updatedDate">June 2008</span></span> | <span class="footerItem">Pacific Northwest National Laboratory</span> | <span class="footerItem">Operated by Battelle for the U.S. Department of Energy</span>
</div>