<form id="siteSearch" method="get" action="http://search.pnl.gov/search">

  <div class="tab">
    <label for="siteSearchQ"><span>Search Site</span></label>
  </div>
  <div class="input">
    <input type="text" name="q" value="" id="siteSearchQ" title="Site-specific search" />
    <input type="image" id="siteSearchSubmit" src="http://www.pnl.gov/images/search_button.png" alt="Search" />
	<input type="hidden" name="as_sitesearch" value="brand.pnl.gov" /> <!--  replace brand.pnl.gov with your URL -->
	<input type="hidden" name="access" value="a" />
	<input type="hidden" name="output" value="xml_no_dtd" />
	<input type="hidden" name="client" value="default_frontend" />
	<input type="hidden" name="site" value="default_collection" />
	<input type="hidden" name="proxystylesheet" value="default_frontend" />
	<input type="hidden" name="as_dt" value="i" />
  </div>
</form>
<div id="rightCol">
	<h2>Right Nav Header</h2>
	<h3>SubHeading 1</h3>
	<ul>
		<li><a href="" id="">Page 1</a></li>
		<li><a href="" id="">Page 2</a></li>
		<li><a href="" id="">Page 3</a></li>
	</ul>

	<h3>SubHeading 2</h3>
	<ul>
		<li><a href="" id="">Page 1</a></li>
		<li><a href="" id="">Page 2</a></li>
		<li><a href="" id="">Page 3</a></li>
	</ul>
	<p><a href="">Another Link &gt;</a></p>
</div>